CONFIG_USE_SEGGER_RTT=n
CONFIG_RTT_CONSOLE=n
CONFIG_LOG_BACKEND_RTT=n
CONFIG_LOG_BACKEND_UART=n
CONFIG_UART_CONSOLE=n
CONFIG_HW_STACK_PROTECTION=n

CONFIG_GPIO=n
CONFIG_I2C=n
CONFIG_SPI=n
CONFIG_ADC=n
CONFIG_SERIAL=n
CONFIG_REGULATOR=n
CONFIG_PWM=n
CONFIG_PWM_STM32=n
CONFIG_MIPI_DBI=n
CONFIG_MIPI_DBI_SPI=n
CONFIG_ST7735R=n
CONFIG_GPIO_PCA95XX=n

CONFIG_DISPLAY=y
CONFIG_SDL_DISPLAY=y
CONFIG_INPUT=y
CONFIG_INPUT_SDL_TOUCH=y