/*
 * google_sans_freetype.h
 * Google Sans SemiBold, 14px, 4bpp (16 levels) bitmap font.
 * Generated by temp/gen_font.py from GoogleSans-SemiBold.ttf.
 * Hint: normal; oversample: 1x; coverage gamma: 1.
 *
 * Glyph set:  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
 */
#ifndef GOOGLE_SANS_FREETYPE_H_
#define GOOGLE_SANS_FREETYPE_H_

#include <stdint.h>

#include "ui_font.h"

extern const ui_font_t google_sans_freetype;

#endif /* GOOGLE_SANS_FREETYPE_H_ */
